controller_list:
    - name: manipulator
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - manipulator/joint_1
        - manipulator/joint_2
        - manipulator/joint_3
        - manipulator/joint_4
        - manipulator/joint_5
        - manipulator/joint_6
    - name: gripper
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - eef_joint_finger_1
        - eef_joint_finger_2